files:
  - source: content/commons/docs/en-us/**/*.md
    translation: content/crowdin/wconfirm/docs/%two_letters_code%/%original_file_name%
  - source: content/commons/navigation/en-us/**/*.yaml
    translation: content/crowdin/wconfirm/navigation/%two_letters_code%/%original_file_name%
